# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Homework14' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homework14
  pod 'Kanna', '~> 5.2'
  pod 'Alamofire', '~> 5.2'

end
